// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXpcPF9BtbT3zGbEf4uFjP5UAzbX_9v0w',
    appId: '1:16818032661:web:7c9741134243bbc39cfe1c',
    messagingSenderId: '16818032661',
    projectId: 'service-book-flutter-vinu',
    authDomain: 'service-book-flutter-vinu.firebaseapp.com',
    databaseURL: 'https://service-book-flutter-vinu-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'service-book-flutter-vinu.appspot.com',
    measurementId: 'G-01NM0S4Y31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKASWhwsX0eqCW-YfsG6WAji8KoAvwzP8',
    appId: '1:16818032661:android:438e9df3586845b19cfe1c',
    messagingSenderId: '16818032661',
    projectId: 'service-book-flutter-vinu',
    databaseURL: 'https://service-book-flutter-vinu-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'service-book-flutter-vinu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAjHfZyEER23XZ5ejN2biL5GuqFOX4yp8',
    appId: '1:16818032661:ios:76550e95afed9c1b9cfe1c',
    messagingSenderId: '16818032661',
    projectId: 'service-book-flutter-vinu',
    databaseURL: 'https://service-book-flutter-vinu-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'service-book-flutter-vinu.appspot.com',
    iosClientId: '16818032661-seavo6humca4n19b47cv9v8gdp28ivm9.apps.googleusercontent.com',
    iosBundleId: 'com.example.databaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAjHfZyEER23XZ5ejN2biL5GuqFOX4yp8',
    appId: '1:16818032661:ios:76550e95afed9c1b9cfe1c',
    messagingSenderId: '16818032661',
    projectId: 'service-book-flutter-vinu',
    databaseURL: 'https://service-book-flutter-vinu-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'service-book-flutter-vinu.appspot.com',
    iosClientId: '16818032661-seavo6humca4n19b47cv9v8gdp28ivm9.apps.googleusercontent.com',
    iosBundleId: 'com.example.databaseTest',
  );
}
